### ISSUE TITLE
Gosu compiler does not create line number entry for implicit return

### ISSUE THREAD

**Issue by roofpig95008** [gosu-lang/gosu-lang#106]
Attached are two sample programs (Gosu and equivalent Java, although Gosu has one more method).  Below the source for the programs is the output from javap -c -l so you can see what the compiler is producing.

If there's no explicit return, javac produces a linenumber entry for the implicit return, corresponding to the closing curly brace of the method.  The Gosu compiler does not produce this entry. This causes the debugger to give very misleading displays in cases where the generated bytecode does a jump to the return (for example, code 20 in function foo())

If.gs contains an additional method with an explicit return, which proves that the gosu compiler does produce a line number entry in this instance. The bug behavior is limited to implicit return.

[example.zip](https://github.com/gosu-lang/gosu-lang/files/965710/example.zip)

**Comment by rsmckinney** [comment]
Note this is only an issue when debugging a Gosu class that is not statically compiled.  At build-time Gosu's type system keeps the parse tree fully intact, this includes all tokens and their source locations and line numbers, which allows the Gosu compiler to generate an implicit return statement with a line number matching the line number corresponding with the function's closing brace.

At runtime, however, for performance reasons the type system dumps part of the parse tree including tokens etc.  Thus their is no line information available for the compiler, which is why there is no line number generated with an implicit return opcode.  This explains the undesirable effect in the debugger where it highlights the wrong line after stepping over an implicit terminal statement.

Again, this behavior only applies to dynamically compiled Gosu classes -- if you statically compile your application classes, this is a non-issue.

In any case, we'll fix this issue by storing a function's last line number in addition to it's first.  The compiler will be changed accordingly.
