### ISSUE TITLE
Variadic functions support

### ISSUE THREAD

**Issue by geofrey** [gosu-lang/gosu-lang#158]
Gosu appears to have some knowledge of varargs, to the point of reporting their parameter types with the Java-style type signature "...". However calling such functions with a traditional comma-separated parameter list is not valid.

For example, the Insurance Suite database API has a function whose parameter list is presented as `select(iQuerySelectColumns : IQuerySelectColumn...)` (It is not clear whether this JAR'd library was written in Java or in Gosu). Writing a call like this, as the function signature suggests:

    select(columnSpec1, columnSpec2, someAggregate, columnSpec3)

produces a compiler error. Instead, the correct approach is to provide the parameters in an array: 

    select({columnSpec1, columnSpec2, someAggregate, columnSpec3})

Is there currently a) Gosu support for declaring and calling variadic functions as such? or, b) any plan to add support in the future?

**Comment by rsmckinney** [comment]
Gosu supports Java var args as follows:

- a var args parameter is optional, it may be omitted in the arg list
- as you point out since a var args parameter is really an array, you can use Gosu array value syntax which is nearly as concise as the Java way, but comes with the added benefit of applying equally well to _any_ array parameter, not just the ellipsis ones
