### ISSUE TITLE
[Question] Why does the source code not make use of tabs?

### ISSUE THREAD

**Issue by Jezza** [gosu-lang/gosu-lang#83]
Just curious as to why the source seems to be using spaces, and not tabs.
Now, I should point out, I don't want to start a flame war.
I'm just curious if it's going to stay that way.

**Comment by DPUkyle** [comment]
Hi and thanks for using Gosu!

Since editors often interpret the indent level of a tab in different ways, we've kept it simple and stuck with spaces.

**Comment by Jezza** [comment]
> [...]editors often interpret the indent level of a tab in different ways[...]

Isn't that the point?
For example, I'm definitely used to seeing a full indentation between a block and a statement, such as an if and its block, but with the current source code, it seems to be a bit random.
Some are indented by 2 spaces, others 4.
Seems to be woefully inconsistent.
If people are used to seeing 2 spaces, you can change tab sizes to be the width of 2 spaces in any good editor.
If GosuLab doesn't provide this functionality, I'd be happy to look into it.
It's just as it stands now, it gets tedious making sure that any change I do I have to convert the indentation to the correct amount of spaces.
It raises the bar on people being able to help, granted anyone who actually wants to implement/fix something would do it regardless, as it gets difficult to read.

**Comment by DPUkyle** [comment]
I agree with you, and as we grow this has been in the back of my mind for a while. Since we are a small project and the core committers work in close proximity with each other, we've been able to tolerate these inconsistencies until now. But I agree, the inconsistent styling makes it difficult to solicit contributions.

So I propose to solve this using a combination of the EditorConfig standard, combined with adding the checkstyle plugin to our build.

I created a branch to experiment with this here: https://github.com/gosu-lang/gosu-lang/tree/checkstyle
Please feel free to have a look and let me know what you think.

We still have the issue that Gosu's creator, Scott (@rsmckinney), prefers an unusual coding style similar to the [Horstmann style](https://en.wikipedia.org/wiki/Indent_style#Horstmann_style), but with additional whitespace before/after parenthesis. So it's one challenge to make checkstyle understand and accommodate this without having to refactor our entire codebase, and another challenge to export the Hosrtmann-eqsue settings in a way that can be imported by contributors.

Oh, one last note about tabs. I stumbled across this [module](http://checkstyle.sourceforge.net/config_whitespace.html#FileTabCharacter) for the checkstyle plugin, whose default behavior is to reject \t characters. I found these reasons interesting:

>  Rationale:
> 
>     * Developers should not need to configure the tab width of their text editors in order to be able to read source code.
>     * From the Apache jakarta coding standards: In a distributed development environment, when the commit messages get sent to a mailing list, they are almost impossible to read if you use tabs.

**Comment by Jezza** [comment]
I definitely think EditorConfig is a way to go, especially if we can just run a formatter over the project or changed files with it before a commit.
I'll take a look at the branch, when I can.

Obviously, I don't want this to sound like I'm having a go at @rsmckinney, whom I'm grateful towards for making this language, but if readability, and more community contributions are desirable, wouldn't it make more sense to adapt a more standardised format?
Such as [Sun's](http://www.oracle.com/technetwork/java/codeconvtoc-136057.html)?
If he wants to keep his style, I understand, I just think it's definitely going to hurt outside productivity.

Regarding the reasons for rejecting \t characters:
> Developers should not need to configure the tab width of their text editors in order to be able to read source code.

That seems like a "everyone can read this style equally", which if anything has taught me, just isn't the case.
The fact that there's so many different style variants in the wiki page alone, only further supports that fact.
Configuring tab size within an editor is much more desirable than enforcing a global indent size.

> From the Apache jakarta coding standards: In a distributed development environment, when the commit messages get sent to a mailing list, they are almost impossible to read if you use tabs.

This I can totally understand. Mailing lists go back years, and can be completely destroyed by tabs. 
I guess my main question would be how often does Gosu end up in a mailing list?

All that aside, I think that it's going to be a lot easier to help, if there's a nicer standard to adhere to. :)
