### ISSUE TITLE
Is this the Design or a Bug

### ISSUE THREAD

**Issue by skis** [gosu-lang/gosu-lang#98]
hi, when I have a complete or multiple conditions as in below snippet, the where condition fails to filter out the elements.

_var list = {1, 2, 3, 5}
list.where( \ elt -> (elt != 2 || elt != 5)).each( \ elt -> {
  print(elt)
})_

Below is what the code in CoreIterableEnhancement.gsx looks like, which appears to support only one condition at a time:

_function where( cond(elt:T): boolean ) : List<T> {
    var result = new ArrayList<T>()
    for( elt in this ) {
      if( cond( elt ) ) {
        result.add( elt )
      }
    }
    return result
  }_

In cases like the snippet I included, this function will not execute perfectly. Was this the intended design or is this a bug?

**Comment by carsongross** [comment]
The logical conditional you have is going to be true for all numbers, since
2 != 5 and 5 !=2 and you have a logical OR in there.

I think the logic you are looking for is something like:

 list.where( \ elt -> elt != 2 && elt != 5 )

(which is kind of the opposite of how we would say it in english,
unfortunately)

Cheers,
Carson

On March 10, 2017 at 7:57:00 AM, skis (notifications@github.com) wrote:

hi, when I have a complete or multiple conditions as in below snippet, the
where condition fails to filter out the elements.




*var list = {1, 2, 3, 5} list.where( \ elt -> (elt != 2 || elt != 5)).each(
\ elt -> { print(elt) })*

Below is what the code in CoreIterableEnhancement.gsx looks like, which
appears to support only one condition at a time:









*function where( cond(elt:T): boolean ) : List { var result = new
ArrayList() for( elt in this ) { if( cond( elt ) ) { result.add( elt ) } }
return result }*

In cases like the snippet I included, this function will not execute
perfectly. Was this the intended design or is this a bug?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gosu-lang/gosu-lang/issues/98>, or mute the thread

**Comment by skis** [comment]
Thanks Carson
