### ISSUE TITLE
Question: Blocks

### ISSUE THREAD

**Issue by skis** [gosu-lang/gosu-lang#99]
Hello,
Is it possible to store a lambda/block/closure expression as a variable? I believe many features that are available in Groovy are also available in Gosu. Just wondering if some like below that is possible in Groovy can be done in Gosu:

_def sum = {x, y -> x + y}_

Thanks

**Comment by carsongross** [comment]
Yep:

  var sum = \ x : int, y : int -> x + y

Cheers,
Carson


On March 13, 2017 at 7:46:02 AM, skis (notifications@github.com) wrote:

Hello,
Is it possible to store a lambda/block/closure expression as a variable? I
believe many features that are available in Groovy are also available in
Gosu. Just wondering if some like below that is possible in Groovy can be
done in Gosu:

*def sum = {x, y -> x + y}*

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/gosu-lang/gosu-lang/issues/99>, or mute the thread

**Comment by skis** [comment]
Thanks Carson.
